### ISSUE TITLE
cannot compile on arduino IDE 2.0.4

### ISSUE THREAD

**Issue by kamilzidek** [things4u/ESP-1ch-Gateway-v6.0#117]
all libraries imported from lib folder unable to compile still some error with initDown? please help...

D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino: In function 'void setup()':
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino:302:2: error: 'initDown' was not declared in this scope
  initDown(&LoraDown);
  ^~~~~~~~
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino:302:2: note: suggested alternative: 'init_oLED'
  initDown(&LoraDown);
  ^~~~~~~~
  init_oLED
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino:408:9: error: 'WlanConnect' was not declared in this scope
  while (WlanConnect(0) <= 0) {
         ^~~~~~~~~~~
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino:516:2: error: 'msg_lLED' was not declared in this scope
  msg_lLED("GET TIME",".");
  ^~~~~~~~
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino:516:2: note: suggested alternative: 'msg_oLED'
  msg_lLED("GET TIME",".");
  ^~~~~~~~
  msg_oLED
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino:517:14: error: 'resolveHost' was not declared in this scope
  ntpServer = resolveHost(NTP_TIMESERVER, 15);
              ^~~~~~~~~~~
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino:567:3: error: 'writeGwayCfg' was not declared in this scope
   writeGwayCfg(_CONFIGFILE, &gwayConfig );
   ^~~~~~~~~~~~
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino:567:3: note: suggested alternative: 'readGwayCfg'
   writeGwayCfg(_CONFIGFILE, &gwayConfig );
   ^~~~~~~~~~~~
   readGwayCfg
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino:607:2: error: 'readSeen' was not declared in this scope
  readSeen(_SEENFILE, listSeen);       // read the seenFile records
  ^~~~~~~~
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino:607:2: note: suggested alternative: 'readUdp'
  readSeen(_SEENFILE, listSeen);       // read the seenFile records
  ^~~~~~~~
  readUdp
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino:644:2: error: 'writeConfig' was not declared in this scope
  writeConfig(_CONFIGFILE, &gwayConfig);     // Write config
  ^~~~~~~~~~~
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino:644:2: note: suggested alternative: 'initConfig'
  writeConfig(_CONFIGFILE, &gwayConfig);     // Write config
  ^~~~~~~~~~~
  initConfig
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino:657:29: error: 'readRegister' was not declared in this scope
 # define printReg(x) {int i=readRegister(x); if(i<=0x0F) Serial.print('0'); Serial.print(i,HEX);}
                             ^~~~~~~~~~~~
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino:658:35: note: in expansion of macro 'printReg'
  Serial.print("RegInvertiQ :: "); printReg(REG_INVERTIQ);  Serial.println();
                                   ^~~~~~~~
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino:657:29: note: suggested alternative: 'writeRegister'
 # define printReg(x) {int i=readRegister(x); if(i<=0x0F) Serial.print('0'); Serial.print(i,HEX);}
                             ^~~~~~~~~~~~
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino:658:35: note: in expansion of macro 'printReg'
  Serial.print("RegInvertiQ :: "); printReg(REG_INVERTIQ);  Serial.println();
                                   ^~~~~~~~
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino:657:29: error: 'readRegister' was not declared in this scope
 # define printReg(x) {int i=readRegister(x); if(i<=0x0F) Serial.print('0'); Serial.print(i,HEX);}
                             ^~~~~~~~~~~~
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino:659:35: note: in expansion of macro 'printReg'
  Serial.print("RegInvertiQ2:: "); printReg(REG_INVERTIQ2); Serial.println();
                                   ^~~~~~~~
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino:657:29: note: suggested alternative: 'writeRegister'
 # define printReg(x) {int i=readRegister(x); if(i<=0x0F) Serial.print('0'); Serial.print(i,HEX);}
                             ^~~~~~~~~~~~
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino:659:35: note: in expansion of macro 'printReg'
  Serial.print("RegInvertiQ2:: "); printReg(REG_INVERTIQ2); Serial.println();
                                   ^~~~~~~~
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino: In function 'void loop()':
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino:689:6: error: 'WlanConnect' was not declared in this scope
  if (WlanConnect(1) < 0) {
      ^~~~~~~~~~~
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino:862:4: error: 'printInt' was not declared in this scope
    printInt(micros(), response);
    ^~~~~~~~
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino:862:4: note: suggested alternative: 'printIP'
    printInt(micros(), response);
    ^~~~~~~~
    printIP
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino:882:4: error: 'printInt' was not declared in this scope
    printInt(micros(), response);
    ^~~~~~~~
D:\OneDrive_SMART\TUKESTL\Projekty\Arduino\1channel_gateway\ESP-1ch-Gateway\src\ESP-sc-gway\ESP-sc-gway.ino:882:4: note: suggested alternative: 'printIP'
    printInt(micros(), response);
    ^~~~~~~~
    printIP
